-- Initial CMS schema for Lutte Berg Orchester.
--
-- Convention notes:
--   IDs are TEXT (UUIDv4 generated by the app via crypto.randomUUID()).
--   Legacy seed IDs ("1", "2", "news-1", ...) are accepted as-is.
--   created_at / updated_at are ISO-8601 TEXT (D1/SQLite idiom; no native DATETIME).
--   `data` columns hold JSON blobs for future freeform extensions.
--   Publication boundary: queries for the public API use WHERE status = 'published'.

CREATE TABLE IF NOT EXISTS site_settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,           -- JSON blob
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sections (
  id                TEXT PRIMARY KEY,
  slug              TEXT NOT NULL UNIQUE,
  title             TEXT NOT NULL,
  short_description TEXT,
  full_description  TEXT,
  hero_media_type   TEXT NOT NULL DEFAULT 'image',   -- 'image' | 'video'
  cover_image       TEXT,
  practical_info    TEXT,
  sort_order        INTEGER NOT NULL DEFAULT 0,
  status            TEXT NOT NULL DEFAULT 'published',
  data              TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sections_status ON sections(status);

CREATE TABLE IF NOT EXISTS child_pages (
  id                TEXT PRIMARY KEY,
  section_id        TEXT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  slug              TEXT NOT NULL,
  title             TEXT NOT NULL,
  short_description TEXT,
  body              TEXT,
  cover_image       TEXT,
  sort_order        INTEGER NOT NULL DEFAULT 0,
  status            TEXT NOT NULL DEFAULT 'published',
  data              TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE(section_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_child_pages_section ON child_pages(section_id);
CREATE INDEX IF NOT EXISTS idx_child_pages_status  ON child_pages(status);

CREATE TABLE IF NOT EXISTS news (
  id         TEXT PRIMARY KEY,
  section_id TEXT REFERENCES sections(id) ON DELETE SET NULL,
  title      TEXT NOT NULL,
  date       TEXT NOT NULL,                  -- ISO yyyy-mm-dd
  excerpt    TEXT,
  body       TEXT,
  image      TEXT,
  status     TEXT NOT NULL DEFAULT 'draft',  -- new content defaults to draft
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_news_status_date ON news(status, date DESC);
CREATE INDEX IF NOT EXISTS idx_news_section     ON news(section_id);

CREATE TABLE IF NOT EXISTS events (
  id          TEXT PRIMARY KEY,
  section_id  TEXT REFERENCES sections(id) ON DELETE SET NULL,
  title       TEXT NOT NULL,
  date        TEXT NOT NULL,
  time        TEXT,
  location    TEXT,
  description TEXT,
  image       TEXT,
  status      TEXT NOT NULL DEFAULT 'draft',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_status_date ON events(status, date);
CREATE INDEX IF NOT EXISTS idx_events_section     ON events(section_id);

CREATE TABLE IF NOT EXISTS media_items (
  id            TEXT PRIMARY KEY,
  section_id    TEXT REFERENCES sections(id) ON DELETE CASCADE,
  child_page_id TEXT REFERENCES child_pages(id) ON DELETE CASCADE,
  type          TEXT NOT NULL,                  -- 'image' | 'youtube'
  url           TEXT NOT NULL,                  -- raw URL as entered (image path OR original YouTube URL)
  video_id      TEXT,                           -- normalized YouTube id (NULL for images)
  embed_url     TEXT,                           -- normalized https://www.youtube.com/embed/<id> (NULL for images)
  title         TEXT,
  caption       TEXT,
  pinned        INTEGER NOT NULL DEFAULT 0,     -- 0 / 1
  sort_order    INTEGER NOT NULL DEFAULT 0,
  status        TEXT NOT NULL DEFAULT 'published',
  context       TEXT,                           -- optional grouping label (e.g. "musaik")
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  CHECK (
    (section_id IS NOT NULL AND child_page_id IS NULL) OR
    (section_id IS NULL AND child_page_id IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_media_section ON media_items(section_id,    type, pinned DESC, sort_order);
CREATE INDEX IF NOT EXISTS idx_media_child   ON media_items(child_page_id, type, pinned DESC, sort_order);
